### ISSUE TITLE
Cannot send messages on an imported conversation - ReferenceError: file is not defined

### ISSUE THREAD

**Issue by MiracleXYZ** [ollama-webui/ollama-webui#189]
**Describe the bug**
Cannot send messages on an imported conversation. The console shows the following error message:

```
Uncaught (in promise) ReferenceError: files is not defined
    at ae (4.72c51156.js:7:945)
    at HTMLTextAreaElement.F (Navbar.fcc8a122.js:47:5766)
```

**To Reproduce**
1. Start a new conversation and get some model responses.
2. Export the conversation, delete, and re-import it.
3. Type some text and try to send the message.

**Expected behavior**
The message should be sent and the model should start responding.

**Screenshots**
<img width="1856" alt="image" src="https://github.com/ollama-webui/ollama-webui/assets/30370926/74eadfc5-eadc-44be-b5a3-a1ac97574dc7">

**Desktop (please complete the following information):**
 - OS: macOS
 - Browser: Arc
 - Version: Version 1.19.1 (43687), Chromium Engine Version 119.0.6045.199

**Additional context**

**Comment by MiracleXYZ** [comment]
Reverting back to `ghcr.io/ollama-webui/ollama-webui@sha256:d88463c203627eb537c39f04085a35a951095474e1948661a0d3fd9b1a570d82` solved this issue. I guess the issue has something to do with [this commit](https://github.com/ollama-webui/ollama-webui/commit/dc7f595448caffbfaf604936f76b2337ef61f68e#diff-2af3510b2da1f806deae850487ac2e517054802c7c9cf714cf68560b048ebb6fR450).

**Comment by tjbck** [comment]
Hi, Thanks for creating this issue. Taking a look now, stay tuned for updates.

**Comment by tjbck** [comment]
The latest release should've fixed your issue, Let me know if the issue still persists, Thanks!

**Comment by MiracleXYZ** [comment]
> The latest release should've fixed your issue, Let me know if the issue still persists, Thanks!

It is now fixed. Thanks!
